### PR TITLE
st7789/st7789_4bit.py little speedup, split=5

### PR DESCRIPTION
**Pull request by IhorNehrutsa**
1) ~1ms speedup with lb = memoryview(self._linebuf)
2)  split=5 in do_refresh() avoided raise ValueError()

### CODE REVIEW

**Review by peterhinch — COMMENTED** [review]
I'm surprised by some of these changes and would appreciate an explanation.

Adding `self.fill(0)` should achieve nothing because a newly initialised bytearray should already be empty. Why is this done?

Using a `memoryview` into `_linebuf` should also make no difference as the purpose of a `memoyview` is to enable zero-cost slicing, and we never slice it. Unless it achieves some magic in `_lcopy`? This seems unlikely as `_lcopy` just sees a linear array of bytes.

I have no objection to any of these changes, but for my own interest I'd like to understand the reasoning or empirical evidence before I merge. Thank you.

**Comment by IhorNehrutsa** [comment]
About self.fill(0)
When I experimented, sometimes (3 or 4 times) after connecting the type C connector to the TTGO display I got a display like this photo. This photo shows the TTGO after powering on (the display backlight is on, but memory is not filled).
P10513-101521
Now I can't reproduce this state and I think that self.fill(0) is unnecessary. I removed it.

I add 
```
    for i in range(len(lut)):
        lut[i] = 0xFF  # set all colors to BLACK
```
to prevent a white screen when the first time self.show() is called in __init__().
The lut has not yet been initialized at init time.

**Comment by IhorNehrutsa** [comment]
About the memoryview.
I tested micropython-nano-gui\gui\demos\aclock.py 
with uncomment time measuring in 
https://github.com/peterhinch/micropython-nano-gui/blob/9085e952156a08597449712d17b27827e5ecdb84/drivers/st7789/st7789_4bit.py#L211

This is output without memoryview
```
lb = self._linebuf
```
>>> %Run -c $EDITOR_CONTENT
46321
46682
46624
46687
46592
46639
46687
46485
46696
46666
51004
46731
46654
46595
46672
46624
46625
46703
46509
46695
46695
51039
46716
46670
46587
46671
46657
46596
46688
46586
46636
46673
46491
46706
46681
51035
46715
46670
46594
46675
46618
46625
46682
46596
Traceback (most recent call last):
  File "<stdin>", line 57, in <module>
  File "<stdin>", line 55, in aclock
KeyboardInterrupt: 

This is output with memoryview
```
lb = memoryview(self._linebuf)
```
>>> %Run -c $EDITOR_CONTENT
46352
45963
45873
45926
45883
45879
45969
45767
45977
45919
50261
45983
45940
45873
45949
45896
45886
45974
45766
45982
45967
45773
45989
45927
45862
45915
45893
45864
45957
45885
45878
45947
45725
Traceback (most recent call last):
  File "<stdin>", line 57, in <module>
  File "<stdin>", line 55, in aclock
KeyboardInterrupt: 
>>> 

The difference in the second run a ~1ms less, but I can't explain it.

**Review by peterhinch — CHANGES_REQUESTED** [review]
Good idea to default black, but this is cheaper:
```python
lut = bytearray(0xff for _ in range(32))
```

**Comment by peterhinch** [comment]
OK, I'm convinced about the memoryview but I don't understand the reason :) Thanks for clarifying.

**Pull request merged**
