### PR TITLE
unix port: add b/w terminal driver (braille/ascii, scrolling/ucurses), add SDL driver (color)

### PR DESCRIPTION
**Pull request by eudoxos**
Uses adapted [drawille](https://github.com/asciimoo/drawille) for braille output, and can use ucurses for terminal clearing (both optional). Not made for high FPS (probably).

Say this in color_setup.py:
```python
from drivers.terminal import Terminal
SSD=Terminal
ssd=SSD(width=196,height=128,curse=True,braille=True)
```
image

### CODE REVIEW

**Comment by eudoxos** [comment]
Quick&dirty driver based on SDL2 (author of 99% of this: Paul Sokolovsky, MIT/zlib licensed): `aclock_large.py` with `color_setup.py` looks like this:

```python
from drivers.usdl2 import FrameBuffer as SSD
ssd=SSD(width=480,height=320)
```

image

**Comment by eudoxos** [comment]
I managed to use micropython buffer as texture and map that to the SDL surface, including scaling. 
```python
from drivers.usdl2 import SDLWindow as SSD
ssd=SSD(width=256,height=256,title='SDL test',scale=3)
```
I just can't get the colors right (the rgb function)... - any hint?

image

**Comment by peterhinch** [comment]
I think this is best progressed as a fork. There are three reasons why I don't intend to merge this:
 * Licensing: like MicroPython my code is MIT licensed and some of this is GPL.
 * The nano-gui library is intended to run on microcontrollers; simplicity and small size is crucial. It can even run on an ESP8266. If code is to be added, it must be in support of that objective.
 * I don't want to undertake the support burden implied by use under Unix.

That said, what you are doing is very worthwhile. I think a fork dedicated to Unix/Braille (removing all my drivers and simplifying the docs) is the way to go with this.

**Comment by eudoxos** [comment]
The intent was to develop *for* microcontrollers *on* desktop (Linux), not to run those drivers on uCs.

I only went quickly at drawille preamble and it "looked like* MIT; but it is in fact AGPL :/ too bad, though most of it could be re-implemented (it is just a special way of putting bits into array).

I understand your reservations and I am closing this PR then.

**Pull request closed without merging**
