### PR TITLE
add sh1106 driver and update docs and create config sample

### PR DESCRIPTION
**Pull request by freemansoft**
Adding sh driver from https://github.com/robert-hh/SH1106 along with sample program and doc updates. Passes the monochrome tests.

This is based on the monochrome driver similar to the ssd1306. 

* Trailing spaces aren't required in the README for lists (bullet or numbered).  It would be great if the README file didn't rely on 2 trailing spaces on some lines for formatting.
* Tested with the monochrome samples - looks good
* The rgb settings were copied from the SSD1306 driver but I don't know if they are correct.

**Note**
The SH1106 driver fails when called from color examples.  There is a commit note on the SSD1306 that says it was made compatible with color (as gray scale) but I dont' understand how that works. I implemented the same rgb() function but the cwriter fails.

### CODE REVIEW

**Comment by peterhinch** [comment]
The rgb method is non-critical. It merely converts and RGB tuple into a single bit for monochrome rendering. Colors in the demos are mainly saturated so they will render in white. Colors with low RGB values will render as black. The cause of the problem is elsewhere.

I think I've allowed the development of `nano-gui` to get ahead of the monochrome drivers. Please could you try the following, to see if this enables the color demos to work. Add this line to the imports:
```python
from drivers.boolpalette import BoolPalette
```
In the constructor save the framebuffer mode (either `MONO_HMSB` or `MONO_VLSB` depending on rotation) and add the line
```python
self.palette = BoolPalette(mode)
```
I think this will enable the color demos to work, but if not please show me any error traceback.

The driver looks as if it took a good deal of effort to write. Congratulations!

**Review by peterhinch — CHANGES_REQUESTED** [review]
Please see my suggestions in the conversation section.

**Comment by freemansoft** [comment]
Added the BoolPallete changes to sh1106.py and the aclock demo now runs.  It provides the expected boundry exceeded messages because the display is 128x64

This shows the new initializer section containing refs to BoolPalette
```
        if self.rotate90:
            # decouple renderbuf and displaybuf
            self.displaybuf = bytearray(self.bufsize)
            # HMSB is required to keep the bit order in the render buffer
            # compatible with byte-for-byte remapping to the display buffer,
            # which is in VLSB. Else we'd have to copy bit-by-bit!
            mode = framebuf.MONO_HMSB
            self.palette = BoolPalette(mode)
            super().__init__(self.renderbuf, self.height, self.width, mode)
        else:
            self.displaybuf = self.renderbuf
            mode = framebuf.MONO_VLSB
            self.palette = BoolPalette(mode)
            super().__init__(self.renderbuf, self.width, self.height, mode)
```

Tested with 
```
	1. cp -r drivers /pyboard
	2. cp -r gui /pyboard
	3. cp setup_examples/sh1106_spi_pico.py /pyboard/color_setup.py
	4. 
	5. repl ~ import gui.demos.aclock
	6. repl ~ import gui.demos.mono_test
```

I wish I could take credit for the driver but it actually came from the location at the top of the file.

**Comment by peterhinch** [comment]
Excellent, thank you.

**Pull request merged**
